Clipy/Clipy

- Clipy.xcodeproj/project.pbxproj
- Clipy/AppDelegate.swift
- Clipy/Utility/LocalizedString.swift
- Clipy/WindowControllers/CPYPreferenceWindowController.swift
- NSLocalizedString → LocalizedString enum
> Modify NSLocalizedString

- .travis.yml
- Clipy/AppDelegate.swift
- Clipy/Extensions/String+Substring.swift
- Clipy/Libraries/Realm/RLMSupport.swift
- Clipy/Managers/CPYSnippetManager.swift
- Clipy/Managers/ClipManager.swift
- Clipy/Managers/HistoryManager.swift
- Clipy/Managers/MenuManager.swift
- Clipy/Views/TableViewCell/CPYImageAndTextCell.swift
- Podfile.lock
- README.md
- Update dependency libraries
- support swift2.2 and Xcode7.3
> Support swift2.2

- Clipy/AppDelegate.swift
- Clipy/Managers/PasteboardManager.swift
- Clipy/Utility/CPYUtilities.swift
- Move `paste()` method to PasteManager
- Change `CGEventTapLocation` event
> Fix paste method

- .travis.yml
- Clipy/WindowControllers/CPYSnippetEditorWindowController.swift
- fastlane/Fastfile
- fastlane/README.md
> #71 Fix auto replace quote text

- Clipy/Models/CPYClipData.swift
- Change hash value
- There is no compatibility with the previous version, pasteboard history will overlap
- Fixed #69
> Change hash value calculation

- Clipy/Models/CPYClipData.swift
> Fix image hash calculation

- Clipy/Managers/HotKeyManager.swift
- Clipy/Preferences/Panels/CPYShortcutsPreferenceViewController.swift
- ClipyTests/HotKeyManagerSpec.swift
- Change to don't use the RxSwift.Variable
> Fix hotkey manager

- Clipy/AppDelegate.swift
- Clipy/Constants.swift
- Clipy/Managers/ClipManager.swift
- Clipy/Models/CPYClipData.swift
- Clipy/Preferences/Panels/en.lproj/CPYBetaPreferenceViewController.xib
- Clipy/Preferences/Panels/ja.lproj/CPYBetaPreferenceViewController.xib
- Clipy/Utility/CPYUtilities.swift
- Podfile
- Podfile.lock
> Implement save screenshot

- Clipy/AppDelegate.swift
- Add a log to find a snippet of bug
> Add log events

- Clipy/Snippets/en.lproj/CPYSnippetsEditorWindowController.xib
- Clipy/Snippets/ja.lproj/CPYSnippetsEditorWindowController.xib
- Fix the display when there is no item at snippets editor
> Fix snippets editor view

- Clipy/AppDelegate.swift
- Clipy/Constants.swift
- Clipy/Preferences/Panels/en.lproj/CPYGeneralPreferenceViewController.xib
- Clipy/Preferences/Panels/ja.lproj/CPYGeneralPreferenceViewController.xib
- Clipy/Utility/CPYUtilities.swift
> Add send crash and error log setting

- Clipy/Extensions/Realm+Migration.swift
> Fix realm migration issue

- .github/CONTRIBUTING.md
- .github/git_message_en.xml
- .github/git_message_ja.xml
- Dangerfile
- Gemfile
- Gemfile.lock
Introduce [danger](https://github.com/danger/danger) for style check of PR 🚀
> Introduction danger

- Clipy/Sources/Models/CPYClipData.swift
> Fix image reading from NSPasteboard

- Clipy/Sources/Models/CPYClipData.swift
- Clipy/Sources/Services/ClipService.swift
> Fix thumbnail image

- Clipy/Sources/Preferences/Panels/en.lproj/CPYMenuPreferenceViewController.xib
- Clipy/Sources/Preferences/Panels/ja.lproj/CPYMenuPreferenceViewController.xib
> Add show menu icons setting

- Clipy/Sources/AppDelegate.swift
- Clipy/Sources/Managers/MenuManager.swift
- Clipy/Sources/Services/ClipService.swift
- Clipy/Sources/Services/DataCleanService.swift
- Clipy/Sources/Services/ExcludeAppService.swift
- Clipy/Sources/Snippets/CPYSnippetsEditorWindowController.swift
- Podfile.lock
- Pods/KeyHolder/Lib/KeyHolder/RecordView.swift
- Pods/Manifest.lock
- Pods/Target Support Files/KeyHolder/Info.plist
- Pods/Target Support Files/KeyHolder/ResourceBundle-KeyHolder-Info.plist
> Fix warnings

- Clipy/Sources/Extensions/NSColor+Hex.swift
> Add supporting color code format

- Clipy/Sources/Services/PasteService.swift
> Fix paste plain text

- Clipy/Sources/Snippets/CPYSnippetsEditorWindowController.swift
> Accept drag and drop a snippet to empty folder

- Clipy/Sources/Preferences/Panels/Base.lproj/CPYExcludeAppPreferenceViewController.xib
ref: https://github.com/Clipy/Clipy/issues/153
> add missing outlets, fix crash on adding exclude applications

- Clipy.xcodeproj/project.pbxproj
- Clipy/Sources/Extensions/Rx/Observable+Void.swift
- Clipy/Sources/Managers/MenuManager.swift
> Reflect preference setting change immediately in main menu

- Clipy.xcodeproj/project.pbxproj
- Clipy/Sources/AppDelegate.swift
- Clipy/Sources/Environments/AppEnvironment.swift
- Clipy/Sources/Environments/Environment.swift
- Clipy/Sources/Managers/MenuManager.swift
- Clipy/Sources/Preferences/CPYPreferencesWindowController.swift
- Clipy/Sources/Preferences/Panels/CPYExcludeAppPreferenceViewController.swift
- Clipy/Sources/Preferences/Panels/CPYShortcutsPreferenceViewController.swift
- Clipy/Sources/Preferences/Panels/CPYTypePreferenceViewController.swift
- Clipy/Sources/Preferences/Panels/CPYUpdatesPreferenceViewController.swift
- Clipy/Sources/Services/ClipService.swift
- Clipy/Sources/Services/DataCleanService.swift
- Clipy/Sources/Services/ExcludeAppService.swift
- Clipy/Sources/Services/HotKeyService.swift
- Clipy/Sources/Services/PasteService.swift
- Clipy/Sources/Snippets/CPYSnippetsEditorWindowController.swift
- Clipy/Sources/Utility/CPYUtilities.swift
Introduced kickstarter style Environments for more easy tests and DI 🎉 
Thanks [kickstarter-ios oss projects](https://github.com/kickstarter/ios-oss/blob/master/Library/AppEnvironment.swift)
> Introduce Environment

- Clipy/Sources/Constants.swift
- Clipy/Sources/Preferences/Panels/Base.lproj/CPYGeneralPreferenceViewController.xib
- Clipy/Sources/Preferences/Panels/Base.lproj/CPYShortcutsPreferenceViewController.xib
- Clipy/Sources/Preferences/Panels/CPYShortcutsPreferenceViewController.swift
- Clipy/Sources/Preferences/Panels/it.lproj/CPYShortcutsPreferenceViewController.strings
- Clipy/Sources/Preferences/Panels/ja.lproj/CPYShortcutsPreferenceViewController.strings
- Clipy/Sources/Services/HotKeyService.swift
- ClipyTests/HotKeyServiceSpec.swift
> Implement clear history shortcut setting

- Clipy/Sources/AppDelegate.swift
- Clipy/Sources/Services/ClipService.swift
When option is pressed when an item in the clips menu is selected the item is deleted.
This feature was present, albeit in a more advanced form, in ClipMenu.
> Adds 'option click' to delete an item in the  clips menu

- Clipy/Sources/Managers/MenuManager.swift
> Add dot after menu number text

- Clipy/Sources/AppDelegate.swift
- Clipy/Sources/Constants.swift
- Clipy/Sources/Preferences/Panels/Base.lproj/CPYBetaPreferenceViewController.xib
- Clipy/Sources/Preferences/Panels/it.lproj/CPYBetaPreferenceViewController.strings
- Clipy/Sources/Preferences/Panels/ja.lproj/CPYBetaPreferenceViewController.strings
- Clipy/Sources/Services/ClipService.swift
- Clipy/Sources/Services/DataCleanService.swift
- Clipy/Sources/Services/PasteService.swift
- Clipy/Sources/Utility/CPYUtilities.swift
Supports deletion after paste and individual deletion of history as beta function. 🎉 
- Related #197 
- Related #184 
- Related #124 
- Related #99
> Paste and Delete

- Clipy/Sources/Snippets/CPYSnippetsEditorWindowController.swift
> Fix snippet editor layout issue on macOS 10.13 High Sierra

- Clipy/Resources/it.lproj/Localizable.strings
- Clipy/Sources/Preferences/Panels/Base.lproj/CPYMenuPreferenceViewController.xib
> Fix Italian localization

- Clipy/Sources/Services/ExcludeAppService.swift
> Support 1Password 7 extensions

- Clipy/Sources/AppDelegate.swift
> Modify to reflect login item setting at startup

- Clipy/Sources/Services/PasteService.swift
Looks for the key that emits the letter "V" and then presses that key.
This fixes the issue where Clipy performs a Command + K when an item is selected with a Dvorak keyboard layout (the physical V key is actually the letter K on Dvorak).
I'm scanning each time because it is possible to switch keyboard layouts while Clipy is running. I considered trying to cache the scan results per input source, but that felt excessive to try and optimize a loop that runs 10's of times.
This code leverages functionality in the Magnet pod which already figures out the key translation as part of its keyboard shortcut support.
> Support input source selection when pasting (including Dvorak)

- Clipy/Generated/LocalizedStrings.swift
- Clipy/Resources/de.lproj/Localizable.strings
- Clipy/Resources/en.lproj/Localizable.strings
- Clipy/Resources/it.lproj/Localizable.strings
- Clipy/Resources/ja.lproj/Localizable.strings
- Clipy/Resources/zh-Hans.lproj/Localizable.strings
- Clipy/Sources/Snippets/CPYSnippetsEditorWindowController.swift
Was previously hard coded to Japanese.
German, Italian and Simplified Chinese I Google Translated so may not be totally accurate but placeholders should anyone provide better translations.
> Localize the placeholder text for Edit Snippet
